# Stage 1: Build the React app
FROM node:alpine as build

WORKDIR /app

COPY package.json ./
COPY yarn.lock ./

RUN yarn install

COPY . ./

RUN yarn build

# Stage 2: Serve the built React app using Nginx
FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]


#  docker build -t prestmit:1.1 . 
#  docker build -t mozeloper/prestmit:1.1 . 
#  docker run -p 4000:80 prestmit:1.1